RECORD_ID = 72677 #35755

totalEvents=10
eventsPerJob=1

jobIndex = list(range(1, int(totalEvents/eventsPerJob)+1))

rule all:
    input:
        expand("results/gen_{jobIndex}.root", jobIndex=jobIndex)


rule fetch_metadata:
    output:
        metadata="record_metadata.json"
    container:
        "docker://cernopendata/cernopendata-client:latest"
    shell:
        """
            cernopendata-client get-metadata --recid {RECORD_ID} > record_metadata.json
        """

rule parse_metadata:
    input:
        metadata="record_metadata.json"
    output:
        cmd_file="cmsDriver_command.txt"    
    container:
        "docker://cernopendata/cernopendata-client:latest"
    shell:
        """
            set -e
            python3 workflow/scripts/parse_metadata.py {input.metadata} {output.cmd_file} 
        """

rule gen:
    input:
        cmd_file="cmsDriver_command.txt"
    output:
        "results/gen_{jobIndex}.root"
    params:
        events=eventsPerJob
    container:
        "docker://cmssw/cc7:latest"
    shell:
        """
        set -e
        export WORKDIR=$(pwd)

        JOB_DIR=$(mktemp -d)
        cd $JOB_DIR

        echo "Sourcing CMS environment"
        export SCRAM_ARCH=slc7_amd64_gcc700

        source /cvmfs/cms.cern.ch/cmsset_default.sh

        scram p CMSSW CMSSW_10_6_30

        cd CMSSW_10_6_30/src/

        echo "Checking WORKDIR"
        ls -lh $WORKDIR/

        mkdir -p Configuration/GenProduction/python/
        cp $WORKDIR/Configuration/GenProduction/python/*.py Configuration/GenProduction/python/

        echo "Reached scramming"
        scram b 

        eval `scramv1 runtime -sh`

        mkdir -p $WORKDIR/results

        export EVENTS={params.events}
        export JOB_INDEX={wildcards.jobIndex}

        echo "Running cmsDriver"
        ls -lh Configuration/GenProduction/python/
        
        eval "$(cat $WORKDIR/{input.cmd_file})"
        
        echo "Directory after cmsDriver:"
        ls -lh

        echo "Running cmsRun"

        cmsRun gen_cfg_{wildcards.jobIndex}.py > cmsRun.log 2>&1 || true

        echo "Listing directories, to better understand what it looks like:"
        ls -lh 

        if ! ls *.root 1> /dev/null 2>&1; then
            echo "[ERROR] cmsRun exited, but no .root file was created"
            echo "[ERROR] Dumping the cmsRun log to see the exact CMS physics error:"
            cat cmsRun.log
            exit 1
        fi

        cp cmsRun.log $WORKDIR/gen_{wildcards.jobIndex}.log


        mv gen_output.root $WORKDIR/{output}

        sync
        sleep 5

        rm -rf $JOB_DIR
        """   