RECORD_ID = 72677 #35755  

totalEvents=5
eventsPerJob=1

jobIndex = list(range(1, int(totalEvents/eventsPerJob)+1))

rule all:
    input:
        expand("results/hlt_{jobIndex}.root", jobIndex=jobIndex)

rule fetch_metadata:
    output:
        metadata="record_metadata.json"
    container:
        "docker://cernopendata/cernopendata-client:latest"
    shell:
        """
            cernopendata-client get-metadata --recid {RECORD_ID} > {output.metadata}
        """

rule parse_gen_metadata:
    input:
        metadata="record_metadata.json"
    output:
        cmd_file="cmsDriver_gen.txt",
        pileup_record="pileup_record_id.txt"
    params:
        get_curl=True,
        step="gen"
    container:
        "docker://cernopendata/cernopendata-client:latest"
    shell:
        """
            set -e
            python3 workflow/scripts/parse_metadata.py {input.metadata} {output.cmd_file} {params.step} {params.get_curl}
        """

rule gen:
    input:
        cmd_file="cmsDriver_gen.txt"
    output:
        "results/gen_{jobIndex}.root"
    params:
        events=eventsPerJob
    container:
        "docker://cmssw/cc7:latest"
    shell:
        """
        set -e
        export WORKDIR=$(pwd)

        JOB_DIR=$(mktemp -d)
        cd $JOB_DIR

        echo "Sourcing CMS environment"
        export SCRAM_ARCH=slc7_amd64_gcc700

        source /cvmfs/cms.cern.ch/cmsset_default.sh

        scram p CMSSW CMSSW_10_6_30

        cd CMSSW_10_6_30/src/

        echo "Checking WORKDIR"
        ls -lh $WORKDIR/

        mkdir -p Configuration/GenProduction/python/
        cp $WORKDIR/Configuration/GenProduction/python/*.py Configuration/GenProduction/python/

        echo "Reached scramming"
        scram b 

        eval `scramv1 runtime -sh`

        mkdir -p $WORKDIR/results

        export EVENTS={params.events}
        export JOB_INDEX={wildcards.jobIndex}

        echo "Running cmsDriver"
        ls -lh Configuration/GenProduction/python/
        
        eval "$(cat $WORKDIR/{input.cmd_file})"
        
        echo "Directory after cmsDriver:"
        ls -lh

        echo "Running cmsRun"

        cmsRun gen_cfg_{wildcards.jobIndex}.py > cmsRun.log 2>&1 || true

        echo "Listing directories, to better understand what it looks like:"
        ls -lh 

        if ! ls *.root 1> /dev/null 2>&1; then
            echo "[ERROR] cmsRun exited, but no .root file was created"
            echo "[ERROR] Dumping the cmsRun log to see the exact CMS physics error:"
            cat cmsRun.log
            exit 1
        fi

        cp cmsRun.log $WORKDIR/gen_{wildcards.jobIndex}.log

        mv gen_output.root $WORKDIR/{output}

        sync
        sleep 5

        rm -rf $JOB_DIR
        """

rule parse_sim_metadata:
    input:
        metadata="record_metadata.json"
    output:
        cmd_file="cmsDriver_sim.txt"
    params:
        get_curl=0,
        step="sim"
    container:
        "docker://cernopendata/cernopendata-client:latest"
    shell:
        """
            set -e
            python3 workflow/scripts/parse_metadata.py {input.metadata} {output.cmd_file} {params.step} {params.get_curl}
        """

rule sim:
    input:
        gen_results="results/gen_{jobIndex}.root",
        cmd_file="cmsDriver_sim.txt"
    output:
        "results/sim_{jobIndex}.root"
    container:
        "docker://cmssw/cc7:latest"
    params:
        events=eventsPerJob
    shell:
        """
        set -e
        export WORKDIR=$(pwd)

        JOB_DIR=$(mktemp -d)
        cd $JOB_DIR

        echo "Sourcing CMS environment"
        export SCRAM_ARCH=slc7_amd64_gcc700

        source /cvmfs/cms.cern.ch/cmsset_default.sh

        scram p CMSSW CMSSW_10_6_30

        cd CMSSW_10_6_30/src/

        scram b
        eval `scramv1 runtime -sh`

        echo "Running SIM workflow"

        export JOB_INDEX={wildcards.jobIndex}
        export EVENTS={params.events}
        export INPUT_FILE=$WORKDIR/{input.gen_results}
        
        echo "Running cmsDriver for SIM"
        eval "$(cat $WORKDIR/{input.cmd_file})"

        echo "Running cmsRun"
        cmsRun sim_cfg_{wildcards.jobIndex}.py > cmsRun.log 2>&1 || true

        echo "Listing directories, to better understand what it looks like:"
        ls -lh 

        if ! ls *.root 1> /dev/null 2>&1; then
            echo "[ERROR] cmsRun exited, but no .root file was created"
            echo "[ERROR] Dumping the cmsRun log to see the exact CMS physics error:"
            cat cmsRun.log
            exit 1
        fi

        cp cmsRun.log $WORKDIR/sim_{wildcards.jobIndex}.log

        mv sim_output.root $WORKDIR/{output}

        sync
        sleep 5

        rm -rf $JOB_DIR
        """

rule predigi2raw:
    input:
        record_id='pileup_record_id.txt'
    output:
        "results/pileup_file.txt"
    container:
        "docker://cernopendata/cernopendata-client:latest"
    shell:
        """
        pileup_recid="$(cat {input.record_id})"
        mkdir -p results
        cernopendata-client get-file-locations --recid $pileup_recid --protocol xrootd > {output}
        """

rule digi2raw:
    input:
        sim="results/sim_{jobIndex}.root",
        pileup="results/pileup_file.txt"
    output:
        "results/digi2raw_{jobIndex}.root"
    container:
        "docker://cmssw/cc7:latest"
    params:
        events=eventsPerJob
    shell:
        """
        set -e
        export WORKDIR=$(pwd)

        JOB_DIR=$(mktemp -d)
        cd $JOB_DIR

        echo "Sourcing CMS environment"
        export SCRAM_ARCH=slc7_amd64_gcc700

        source /cvmfs/cms.cern.ch/cmsset_default.sh

        scram p CMSSW CMSSW_10_6_30

        cd CMSSW_10_6_30/src/

        scram b
        eval `scramv1 runtime -sh`

        PILEUP_URL=$(sed -n '{wildcards.jobIndex}p' $WORKDIR/{input.pileup})

        echo "Running DIGI2RAW workflow"

        echo "Running cmsDriver for DIGI2RAW"
        cmsDriver.py --python_filename digi2raw_cfg_{wildcards.jobIndex}.py \\
        --eventcontent PREMIXRAW  \\
        --datatier GEN-SIM-DIGI \\
        --fileout file:digi2raw_output.root \\
        --pileup_input "$PILEUP_URL" \\
        --conditions 106X_mcRun2_asymptotic_v13 \\
        --step DIGI,DATAMIX,L1,DIGI2RAW \\
        --procModifiers premix_stage2 \\
        --geometry DB:Extended \\
        --filein file:$WORKDIR/{input.sim} \\
        --datamix PreMix \\
        --era Run2_2016 \\
        --runUnscheduled \\
        --no_exec \\
        --mc \\
        -n {params.events}

        echo "Running cmsRun"
        cmsRun digi2raw_cfg_{wildcards.jobIndex}.py > cmsRun.log 2>&1 || true

        echo "Listing directories, to better understand what it looks like:"
        ls -lh 

        if ! ls *.root 1> /dev/null 2>&1; then
            echo "[ERROR] cmsRun exited, but no .root file was created"
            echo "[ERROR] Dumping the cmsRun log to see the exact CMS physics error:"
            cat cmsRun.log
            exit 1
        fi

        cp cmsRun.log $WORKDIR/digi2raw_{wildcards.jobIndex}.log

        mv digi2raw_output.root $WORKDIR/{output}

        sync
        sleep 5

        rm -rf $JOB_DIR
        """

rule hlt:
    input:
        "results/digi2raw_{jobIndex}.root"
    output:
        "results/hlt_{jobIndex}.root"
    container:
        "docker://cmssw/cc7:latest"
    params:
        events=eventsPerJob
    shell:
        """
        set -e
        export WORKDIR=$(pwd)

        JOB_DIR=$(mktemp -d)
        cd $JOB_DIR

        echo "Sourcing CMS environment"
        export SCRAM_ARCH=slc7_amd64_gcc530

        source /cvmfs/cms.cern.ch/cmsset_default.sh

        scram p CMSSW CMSSW_8_0_33_UL

        cd CMSSW_8_0_33_UL/src/

        scram b
        eval `scramv1 runtime -sh`

        echo "Running HLT workflow"

        cmsDriver.py --python_filename hlt_cfg_{wildcards.jobIndex}.py \\
        --eventcontent RAWSIM  \\
        --outputCommand "keep *_mix_*_*,keep *_genPUProtons_*_*" \\
        --datatier GEN-SIM-RAW \\
        --inputCommands "keep *","drop *_*_BMTF_*","drop *PixelFEDChannel*_*_*_*" \\
        --fileout file:hlt_output.root \\
        --conditions 80X_mcRun2_asymptotic_2016_TrancheIV_v6 \\
        --customise_commands 'process.source.bypassVersionCheck = cms.untracked.bool(True)' \\
        --step HLT:25ns15e33_v4 \\
        --geometry DB:Extended \\
        --filein file:$WORKDIR/{input} \\
        --era Run2_2016 \\
        --no_exec \\
        --mc \\
        -n {params.events}

        echo "Running cmsRun"
        cmsRun hlt_cfg_{wildcards.jobIndex}.py > cmsRun.log 2>&1 || true

        echo "Listing directories, to better understand what it looks like:"
        ls -lh 

        if ! ls *.root 1> /dev/null 2>&1; then
            echo "[ERROR] cmsRun exited, but no .root file was created"
            echo "[ERROR] Dumping the cmsRun log to see the exact CMS physics error:"
            cat cmsRun.log
            exit 1
        fi

        cp cmsRun.log $WORKDIR/hlt_{wildcards.jobIndex}.log

        mv hlt_output.root $WORKDIR/{output}

        sync
        sleep 5

        rm -rf $JOB_DIR
        """

    

        
