BASE_CONTAINER="docker://gitlab-registry.cern.ch/cms-cloud/cmssw-docker/cc7-cms"
OPENDATA_CONTAINER="docker://cernopendata/cernopendata-client:latest"

RECORD_ID=config.get("record_id", 0)
totalEvents=config.get("events", 0)
eventsPerJob=2
EOS_PATH=config.get("eos_outdir", "not found")


jobIndex = list(range(1, int(totalEvents/eventsPerJob)+1))

CLEANUP_SHELL = """
    set -e

    rm {EOS_PATH}/results/{params.step}_{wildcards.jobIndex}.root
    
    mkdir -p results/cleanup
    echo "Cleanup done" > results/cleanup/{params.step}_cleanup_{wildcards.jobIndex}_confirm.txt
"""

MAIN_STEP_SHELL = """
    set -e
    export WORKDIR=$(pwd)

    JOB_DIR=$(mktemp -d)
    cd $JOB_DIR

    echo "Sourcing CMS environment"
    eval "$(cat $WORKDIR/{input.environment})"

    echo "Checking WORKDIR"
    ls -lh $WORKDIR/

    export STEP={params.step}
    if [ "$STEP" = "gen" ]
    then
        mkdir -p Configuration/GenProduction/python/
        cp $WORKDIR/Configuration/GenProduction/python/*.py Configuration/GenProduction/python/
    else
        export INPUT_FILE={EOS_PATH}/results/{params.prev_step}_{wildcards.jobIndex}.root
    fi 

    if [ "$STEP" == "digi2raw" ]
    then
        export PILEUP_URL=$(sed -n '{wildcards.jobIndex}p' $WORKDIR/{params.pileup})
    fi

    echo "Reached scramming"
    scram b 

    eval `scramv1 runtime -sh`

    mkdir -p $WORKDIR/results

    export EVENTS={params.events}
    export JOB_INDEX={wildcards.jobIndex}

    echo "Running cmsDriver"
    
    eval "$(cat $WORKDIR/{input.cmd_file})"
    
    echo "Directory after cmsDriver:"
    ls -lh

    echo "Running {params.step} cmsRun"

    mkdir -p $WORKDIR/cfg_files
    cat <<EOF >> {params.step}_cfg_{wildcards.jobIndex}.py

workflow_seed = 12345 + int({wildcards.jobIndex})

for param in process.RandomNumberGeneratorService.parameterNames_():
    module = getattr(process.RandomNumberGeneratorService, param)
    if hasattr(module, 'initialSeed'):
        module.initialSeed = cms.untracked.uint32(workflow_seed)
EOF
        
    cp {params.step}_cfg_{wildcards.jobIndex}.py $WORKDIR/cfg_files/{params.step}_cfg_{wildcards.jobIndex}.py

    cmsRun {params.step}_cfg_{wildcards.jobIndex}.py > cmsRun.log 2>&1 || true

    echo "Listing directories, to better understand what it looks like:"
    ls -lh 

    if ! ls *.root 1> /dev/null 2>&1; then
        echo "[ERROR] cmsRun exited, but no .root file was created"
        echo "[ERROR] Dumping the cmsRun log to see the exact CMS physics error:"
        cat cmsRun.log
        exit 1
    fi

    cp cmsRun.log $WORKDIR/{params.step}_{wildcards.jobIndex}.log
    
    mkdir -p {EOS_PATH}/results && cp {params.step}_output.root {EOS_PATH}/results/{params.step}_{wildcards.jobIndex}.root

    sync
    sleep 5

    echo "{params.step} step done" > $WORKDIR/results/{params.step}_{wildcards.jobIndex}_confirm.txt
    rm -rf $JOB_DIR
    """

rule all:
    input:
        "results/comparison_report.csv"

rule fetch_metadata:
    output:
        metadata=temporary("record_metadata.json")
    container:
        OPENDATA_CONTAINER
    shell:
        """
        cernopendata-client get-metadata --recid {RECORD_ID} > {output.metadata}
        """

rule parse_gen_metadata:
    input:
        metadata="record_metadata.json"
    output:
        temporary("gen_env.txt"),
        cmd_file=temporary("cmsDriver_gen.txt")
    params:
        step="gen"
    container:
        OPENDATA_CONTAINER
    shell:
        """
        set -e
        python3 workflow/scripts/parse_metadata.py {input.metadata} {output.cmd_file} {params.step}
        """

rule gen:
    input:
        cmd_file="cmsDriver_gen.txt",
        environment="gen_env.txt"
    output:
        temporary("results/gen_{jobIndex}_confirm.txt")
    params:
        events=eventsPerJob,
        step="gen",
        prev_step="dummy",
        pileup="dummy"
    container:
        BASE_CONTAINER
    shell:
        MAIN_STEP_SHELL

rule parse_sim_metadata:
    input:
        metadata="record_metadata.json"
    output:
        temporary("pileup_record_id.txt"),
        temporary("sim_env.txt"),
        cmd_file=temporary("cmsDriver_sim.txt")
    params:
        step="sim"
    container:
        OPENDATA_CONTAINER
    shell:
        """
        set -e
        python3 workflow/scripts/parse_metadata.py {input.metadata} {output.cmd_file} {params.step}
        """

rule sim:
    input:
        "results/gen_{jobIndex}_confirm.txt",
        cmd_file="cmsDriver_sim.txt",
        environment="sim_env.txt"
    output:
        temporary("results/sim_{jobIndex}_confirm.txt")
    container:
        BASE_CONTAINER
    params:
        events=eventsPerJob,
        step="sim",
        prev_step="gen",
        pileup="dummy"
    shell:
        MAIN_STEP_SHELL

rule gen_cleanup:
    input:
        "results/sim_{jobIndex}_confirm.txt"
    output:
        "results/cleanup/gen_cleanup_{jobIndex}_confirm.txt"
    params:
        step="gen"
    container:
        BASE_CONTAINER
    shell:
        CLEANUP_SHELL

rule predigi2raw:
    input:
        record_id='pileup_record_id.txt'
    output:
        temporary("results/pileup_file.txt")
    container:
        OPENDATA_CONTAINER
    shell:
        """
            pileup_recid="$(cat {input.record_id})"
            mkdir -p results
            cernopendata-client get-file-locations --recid $pileup_recid --protocol xrootd > {output}
        """

rule parse_digi2raw_metadata:
    input:
        metadata="record_metadata.json"
    output:
        temporary("digi2raw_env.txt"),
        cmd_file=temporary("cmsDriver_digi2raw.txt")
    params:
        step="digi2raw"
    container:
        OPENDATA_CONTAINER
    shell:
        """
        python3 workflow/scripts/parse_metadata.py {input.metadata} {output.cmd_file} {params.step}
        """

rule digi2raw:
    input:
        "results/cleanup/gen_cleanup_{jobIndex}_confirm.txt",
        "results/sim_{jobIndex}_confirm.txt",
        pileup="results/pileup_file.txt",
        cmd_file="cmsDriver_digi2raw.txt",
        environment="digi2raw_env.txt"
    output:
        temporary("results/digi2raw_{jobIndex}_confirm.txt")
    container:
        BASE_CONTAINER
    resources:
        digi2raw_connections=1
    params:
        events=eventsPerJob,
        step="digi2raw",
        prev_step="sim",
        pileup="results/pileup_file.txt"
    shell:
        MAIN_STEP_SHELL

rule sim_cleanup:
    input:
        "results/digi2raw_{jobIndex}_confirm.txt"
    output:
        "results/cleanup/sim_cleanup_{jobIndex}_confirm.txt"
    params:
        step="sim"
    container:
        BASE_CONTAINER
    shell:
        CLEANUP_SHELL

rule parse_hlt_metadata:
    input:
        metadata="record_metadata.json"
    output:
        temporary("hlt_env.txt"),
        cmd_file=temporary("cmsDriver_hlt.txt")
    params:
        step="hlt"
    container:
        OPENDATA_CONTAINER
    shell:
        """
        python3 workflow/scripts/parse_metadata.py {input.metadata} {output.cmd_file} {params.step}
        """

rule hlt:
    input:
        "results/cleanup/sim_cleanup_{jobIndex}_confirm.txt",
        "results/digi2raw_{jobIndex}_confirm.txt",
        cmd_file="cmsDriver_hlt.txt",
        environment="hlt_env.txt"
    output:
        temporary("results/hlt_{jobIndex}_confirm.txt")
    container:
        BASE_CONTAINER
    params:
        events=eventsPerJob,
        step="hlt",
        prev_step="digi2raw",
        pileup="dummy"
    shell:
        MAIN_STEP_SHELL

rule digi2raw_cleanup:
    input:
        "results/hlt_{jobIndex}_confirm.txt"
    output:
        "results/cleanup/digi2raw_cleanup_{jobIndex}_confirm.txt"
    params:
        step="digi2raw"
    container:
        BASE_CONTAINER
    shell:
        CLEANUP_SHELL

rule parse_reco_metadata:
    input:
        metadata="record_metadata.json"
    output:
        temporary("reco_env.txt"),
        cmd_file=temporary("cmsDriver_reco.txt")
    params:
        step="reco"
    container:
        OPENDATA_CONTAINER
    shell:
        """
        set -e
        python3 workflow/scripts/parse_metadata.py {input.metadata} {output.cmd_file} {params.step}
        """

rule reco:
    input:
        "results/cleanup/digi2raw_cleanup_{jobIndex}_confirm.txt",
        "results/hlt_{jobIndex}_confirm.txt",
        cmd_file="cmsDriver_reco.txt",
        environment="reco_env.txt"
    output:
        temporary("results/reco_{jobIndex}_confirm.txt")
    container:
        BASE_CONTAINER
    params:
        events=eventsPerJob,
        step="reco",
        prev_step="hlt",
        pileup="dummy"
    resources:
        kubernetes_memory_limit='8Gi'
    shell:
        MAIN_STEP_SHELL

rule hlt_cleanup:
    input:
        "results/reco_{jobIndex}_confirm.txt"
    output:
        "results/cleanup/hlt_cleanup_{jobIndex}_confirm.txt"
    params:
        step="hlt"
    container:
        BASE_CONTAINER
    shell:
        CLEANUP_SHELL

rule parse_pat_metadata:
    input:
        metadata="record_metadata.json"
    output:
        temporary("pat_env.txt"),
        cmd_file=temporary("cmsDriver_pat.txt")
    params:
        step="pat"
    container:
        OPENDATA_CONTAINER
    shell:
        """
        set -e
        python3 workflow/scripts/parse_metadata.py {input.metadata} {output.cmd_file} {params.step}
        """

rule pat:
    input:
        "results/cleanup/hlt_cleanup_{jobIndex}_confirm.txt",
        "results/reco_{jobIndex}_confirm.txt",
        environment="pat_env.txt",
        cmd_file="cmsDriver_pat.txt"
    output:
        temporary("results/pat_{jobIndex}_confirm.txt")
    params:
        events=eventsPerJob,
        step="pat",
        prev_step="reco",
        pileup="dummy"
    container:
        BASE_CONTAINER 
    shell:
        MAIN_STEP_SHELL

rule reco_cleanup:
    input:
        "results/pat_{jobIndex}_confirm.txt"
    output:
        "results/cleanup/reco_cleanup_{jobIndex}_confirm.txt"
    params:
        step="reco"
    container:
        BASE_CONTAINER
    shell:
        CLEANUP_SHELL

rule parse_nano_metadata:
    input:
        metadata="record_metadata.json"
    output:
        temporary("nano_env.txt"),
        cmd_file=temporary("cmsDriver_nano.txt")
    params:
        step="nano"
    container:
        OPENDATA_CONTAINER
    shell:
        """
        set -e
        python3 workflow/scripts/parse_metadata.py {input.metadata} {output.cmd_file} {params.step}
        """

rule nano:
    input:
        "results/cleanup/reco_cleanup_{jobIndex}_confirm.txt",
        "results/pat_{jobIndex}_confirm.txt",
        environment="nano_env.txt",
        cmd_file="cmsDriver_nano.txt"
    output:
        temporary("results/nano_{jobIndex}_confirm.txt")
    params:
        events=eventsPerJob,
        step="nano",
        prev_step="pat",
        pileup="dummy"
    container:
        BASE_CONTAINER
    shell:
        MAIN_STEP_SHELL

rule pat_cleanup:
    input:
        "results/nano_{jobIndex}_confirm.txt"
    output:
        "results/cleanup/pat_cleanup_{jobIndex}_confirm.txt"
    params:
        step="pat"
    container:
        BASE_CONTAINER
    shell:
        CLEANUP_SHELL

rule merge_nano:
    input:
        expand("results/cleanup/pat_cleanup_{jobIndex}_confirm.txt", jobIndex=jobIndex),
        expand("results/nano_{jobIndex}_confirm.txt", jobIndex=jobIndex)
    output:
        merged_local=temporary("results/nano_merged.root")
    params:
        eos_inputs=" ".join([f"{EOS_PATH}/results/nano_{i}.root" for i in jobIndex]),
        eos_output=f"{EOS_PATH}/results/nano_merged.root"
    container:
        BASE_CONTAINER
    shell:
        """
        set -e
        export WORKDIR=$(pwd)

        echo "Sourcing CMS environment to get ROOT..."
        export SCRAM_ARCH=slc7_amd64_gcc700
        source /cvmfs/cms.cern.ch/cmsset_default.sh
        
        scram p CMSSW CMSSW_10_6_30
        cd CMSSW_10_6_30/src/
        eval `scramv1 runtime -sh`
        cd ../../
        
        echo "Merging all NanoAOD files..."
        python $WORKDIR/workflow/scripts/haddnano.py {output.merged_local} {params.eos_inputs}

        cp {output.merged_local} {params.eos_output}
        """

rule histogram_results:
    input:
        merged_nano="results/nano_merged.root"
    output:
        report="results/comparison_report.csv" 
    params:
        eos_output=f"{EOS_PATH}/results/comparison_report.csv"
    container:
        "python:3.11-slim" 
    shell:
        """
        set -e 
        export WORKDIR=$(pwd)

        echo "Setting up local Python environment"
        mkdir -p $WORKDIR/my_python_libs

        echo "Installing required packages"
        pip install --no-cache-dir uproot awkward numpy pandas boost_histogram scipy --break-system-packages --target $WORKDIR/my_python_libs

        export PYTHONPATH=$WORKDIR/my_python_libs:$PYTHONPATH

        echo "Downloading reference data file"
        python3 -c "import urllib.request; urllib.request.urlretrieve('https://opendata.cern.ch/eos/opendata/cms/mc/RunIISummer20UL16NanoAODv9/WWTo2L2Nu_TuneCP5_DoubleScattering_13TeV-pythia8/NANOAODSIM/106X_mcRun2_asymptotic_v17-v2/50000/C04CAA8D-3FA5-964C-8D54-1B4601CFD366.root', 'reference_data.root')"

        echo "Running statistical comparison"
        python3 workflow/scripts/Stat_comparison.py {input.merged_nano} reference_data.root {output.report}

        cp {output.report} {params.eos_output}
        """